


###
# @name register 注册
POST {{$dotenv baseUrl}}/api/user/register HTTP/1.1
Content-Type: application/json

{
	username : "admin", 
	password : "admin123", 
	mobile : ""
}

###
# @name login 登录
POST {{$dotenv baseUrl}}/api/user/login HTTP/1.1
Content-Type: application/json

{
	username : "", 
	password : ""
}

###
# @name getUserInfo 获取用户信息
GET {{$dotenv baseUrl}}/api/user/:id HTTP/1.1

###
# @name searchUser 用户搜索
GET {{$dotenv baseUrl}}/api/user/search HTTP/1.1
